3 all profiles will require the service to be described by openapi
EURODEO/rodeo-edr-profile pull request #15
Opened 2024-09-26 07:23 UTC by havardf

2024-09-26 10:23 UTC, tomkralidis requested changes

2024-09-26 10:23 UTC, tomkralidis commented on standard/requirements/requirements_class_core.adoc
> +|Pre-conditions |The WebAPI conforms to OGC API - Environmental Data Retrieval - Part 1: Core, Requirements Class: Core and Requirements Class: Collections
WebAPI -> API (apply across entire PR).

2024-09-26 10:23 UTC, tomkralidis commented on standard/sections/clause_7_core.adoc
> +An OpenAPI specification provides machine-readable description of the WebAPI interface
An OpenAPI document provides a machine-readable description of the API interface.

2024-09-26 10:23 UTC, tomkralidis commented on standard/requirements/core/REQ_openapi.adoc
> +^|A |A WebAPI SHALL be described with an OpenAPI specification of version 3.1 or higher.
An API definition SHALL be described using an OpenAPI document (version 3.1 or higher).

2024-09-26 10:23 UTC, tomkralidis commented on standard/requirements/core/REQ_openapi.adoc
> +^|B |The openapi specification SHALL be formatted as a `JSON` file.
The OpenAPI document SHALL be encoded as JSON.

2024-09-26 10:23 UTC, tomkralidis commented on standard/requirements/core/REQ_openapi.adoc
> +^|C |The WebAPI SHALL implement all capabilities described in the OpenAPI specification.
I'm not sure the API should support ALL of OpenAPI per se.  Or do we mean that the API needs to support whatever is defined in the OpenAPI document.  Do we need this requirement?

2024-09-26 10:23 UTC, tomkralidis commented on standard/requirements/core/REQ_openapi.adoc
> +^|D |The openapi specification SHALL be listed in `links` on the landingpage with `rel` `service-desc`.
The OpenAPI document SHALL be made available in the API Landing Page as a link object with a relation type of `service-desc` and content type of `application/vnd.oai.openapi+json;version=3.1`.

2024-09-26 10:23 UTC, tomkralidis commented on standard/requirements/core/REQ_openapi.adoc
> +^|E |The documentation site for the WebAPI service, which includes api reference documentation, SHALL be listed in `links` on the landingpage with `rel` `service-doc`.
API documentation SHALL be made available in the API Landing Page as a link object with a relation type of `service-doc` and content type of `text/html`.

2024-09-26 10:23 UTC, tomkralidis commented on standard/abstract_tests/core/ATS_test_openapi.adoc
> +test-purpose:: Validate that a RODEO EDR Profile WebAPI provides an OpenAPI specification
Validate that a RODEO EDR Profile provides an API definition using an OpenAPI document

2024-09-26 10:23 UTC, tomkralidis commented on standard/abstract_tests/core/ATS_test_openapi.adoc
> +Check that the value of the returned HTTP status header is 200 and check that the response body is a valid OpenAPI specification of version 3.1 or higher.
Check that the value of the returned HTTP status header is 200 and check that the response body is a valid OpenAPI document of version 3.1 or higher.

2024-09-26 10:23 UTC, tomkralidis commented on standard/abstract_tests/core/ATS_test_openapi.adoc
> +Check that the value of the returned HTTP status header is 200 and that the HTTP response header `Content-Type` contains `text/html`
Check that the value of the returned HTTP status header is 200 and that the HTTP response header `Content-Type` contains `text/html`.

2024-09-26 10:23 UTC, tomkralidis commented on standard/abstract_tests/core/ATS_test_openapi.adoc
> +In the `links` array in the landing page response, find the object with `rel` set to `service-desc`.
In the `links` array in the landing page response, find the object with `rel` set to `service-desc` and `type` set to `application/vnd.oai.openapi+json;version=3.1`.

2024-09-26 10:35 UTC, havardf commented on standard/requirements/requirements_class_core.adoc
> +|Pre-conditions |The WebAPI conforms to OGC API - Environmental Data Retrieval - Part 1: Core, Requirements Class: Core and Requirements Class: Collections
Why? Because the Web part is implied in this context? Or for consistency with other documents?

2024-09-26 10:37 UTC, tomkralidis commented on standard/requirements/requirements_class_core.adoc
> +|Pre-conditions |The WebAPI conforms to OGC API - Environmental Data Retrieval - Part 1: Core, Requirements Class: Core and Requirements Class: Collections
Consistency.

2024-09-26 10:40 UTC, havardf commented on standard/requirements/core/REQ_openapi.adoc
> +^|C |The WebAPI SHALL implement all capabilities described in the OpenAPI specification.
Yes, good catch, defined in the OpenAPI document is what I meant.  I agree its kind of superflous. Its there for two reasons:
- It mirrors the requirement in EDR: https://docs.ogc.org/DRAFTS/19-086r7.html#req_oas30_oas-impl
- I have seen several services which have an openapi document which include a set of data queries. but not all of the collections served by that service provide all the data queries, hence a client made from en openapi definition will get into trouble. Maybe there is a better way of guarding against this?

2024-09-26 10:47 UTC, tomkralidis commented on standard/requirements/core/REQ_openapi.adoc
> +^|C |The WebAPI SHALL implement all capabilities described in the OpenAPI specification.
Ah, ok.  True, some implementations likely copy/paste from an example without realizing the implications.

Then perhaps the following:

1. Update requirement to `The API SHALL implement all capabilities described in the OpenAPI document.`
2. Add an abstract test that specifically invokes each endpoint (path) defined in the OpenAPI document?  The question then becomes how intelligent such a query is and what query parameters are required/how to define.  Or a simple test that checks that each path defined is not a 404 to ensure parity.

2024-09-26 12:42 UTC, tomkralidis commented on standard/requirements/core/REQ_openapi.adoc
> +^|E |The documentation site for the WebAPI service, which includes api reference documentation, SHALL be listed in `links` on the landingpage with `rel` `service-doc`.
Agree, `text/html` is usually enough and encoding can usually be handled from the HTTP response.

2024-09-26 12:51 UTC, havardf commented on standard/requirements/core/REQ_openapi.adoc
> +^|C |The WebAPI SHALL implement all capabilities described in the OpenAPI specification.
Hm, I agree this would need to be tested. I will think a bit about this before updating.

2024-10-04 07:44 UTC, havardf commented
@tomkralidis Have your requested changes been addressed ok? If so, could you just merge the PR?

2024-10-05 04:05 UTC, tomkralidis approved these changes

2024-10-05 04:05 UTC, merged