Add constraints for temporal, spatial and vertical extent.
EURODEO/rodeo-edr-profile pull request #32
Opened 2024-11-19 09:30 UTC by havardf

2024-12-12 22:40 UTC, tomkralidis requested changes

2024-12-12 22:40 UTC, tomkralidis commented on profiles/observations/observations.md
> +      "href": "https://api.example.com/",
`https://api.example.com/` -> `https://example.com/api/`

(apply globally)

2024-12-12 22:40 UTC, tomkralidis commented on standard/requirements/core/REQ_collection_vertical_extent.adoc
> +^|A |If `extent.vertical` is defined, the value of `extent.vertical.vrs` SHOULD be one the following values: `Pressure level in hPa`, `Geopotential height in gpm`, `Geometrical altitude above mean se
is this is Requirement or Recommendation?  If Requirement, then SHOULD -> SHALL.  Else, move this file to `standard/recommendations/core/REC_collection_vertical_extent.adoc` and change accordingly.

2024-12-13 09:13 UTC, havardf commented on standard/requirements/core/REQ_collection_vertical_extent.adoc
> +^|A |If `extent.vertical` is defined, the value of `extent.vertical.vrs` SHOULD be one the following values: `Pressure level in hPa`, `Geopotential height in gpm`, `Geometrical altitude above mean se
Right! I was not aware that there were separate sections for these things. Its a SHOULD, so I will move it. I might have made this mistake other places as well, so I will go through the document.

2024-12-16 16:22 UTC, havardf commented on standard/requirements/core/REQ_collection_vertical_extent.adoc
> +^|A |If `extent.vertical` is defined, the value of `extent.vertical.vrs` SHOULD be one the following values: `Pressure level in hPa`, `Geopotential height in gpm`, `Geometrical altitude above mean se
@tomkralidis How does recommendations fit into the structure of the standards document? E.g should I add recommendations under the `Requirements Class "Core"` section in file `sections/clause_7_core.adoc`? And if not, where do I link up the file so it will show up in the document?

2024-12-16 21:03 UTC, tomkralidis commented on standard/requirements/core/REQ_collection_vertical_extent.adoc
> +^|A |If `extent.vertical` is defined, the value of `extent.vertical.vrs` SHOULD be one the following values: `Pressure level in hPa`, `Geopotential height in gpm`, `Geometrical altitude above mean se
Good question @havardf.  Briefly:

A Requirements Class has the following setup:

- requirements (SHALL)
- recommendations (SHOULD)
- permissions (MAY)

Each requirement/recommendation/permission is its own file.

A Conformance Class (abstract tests) implements all requirements in a requirements class (not recommendations or permissions).

Each abstract test is its own file.

Taking `Requirements Class "Core" as an example:

- requirement files go in `requirements/core`
- recommendation/permission files go in `recommendations/core`

Having said this, for this PR, you would rename the file into `standard/recommendations/core/foo.adoc` and refer to it from the relevant clause (i.e. clause 7 for core, clause 8 for in-situ observations).

2024-12-18 12:15 UTC, havardf commented on standard/requirements/core/REQ_collection_vertical_extent.adoc
> +^|A |If `extent.vertical` is defined, the value of `extent.vertical.vrs` SHOULD be one the following values: `Pressure level in hPa`, `Geopotential height in gpm`, `Geometrical altitude above mean se
I have to include abstracts tests here also; I see.

2024-12-18 13:07 UTC, tomkralidis requested changes

2024-12-18 13:07 UTC, tomkralidis commented on standard/abstract_tests/core/ATS_test_collection_spatial_extent.adoc
> +For each object in `collections` array, for each object in the `data_queries` array, if `crs_details` is specified, check that one of the objects in the `crs_details` array has a `crs`` property set
For each object in `collections` array, for each object in the `data_queries` array, if `crs_details` is specified, check that one of the objects in the `crs_details` array has a `crs` property set to `OGC:CRS84`.

(i.e. there is an extra backtick in \`crs\`\`.

2024-12-19 13:54 UTC, mrauhala approved these changes
Looks good

2024-12-19 15:04 UTC, tomkralidis commented
We still need to ensure any example URLs are updated from https://api.example.com to https://example.org/api (applying globally).

2024-12-19 16:04 UTC, havardf commented
> We still need to ensure any example URLs are updated from https://api.example.com to https://example.org/api (applying globally).

Happy to make the change, but why is it important for it to be `https://example.org/api` ? For consistency across  ogc standard documents?

2024-12-19 16:23 UTC, havardf commented
> > > We still need to ensure any example URLs are updated from https://api.example.com to https://example.org/api (applying globally).
> > 
> > 
> > Happy to make the change, but why is it important for it to be `https://example.org/api` ? For consistency across ogc standard documents?
> 
> Convention. `https://api.example.com` will literally 404. `https://example.org/api` will 200 with a sensible explanation to a user, so as not to think something is "broken" in the specification. Some specifications use actual live endpoints, which I disagree with, given link rot and potentially unnecessary traffic to a live service per se.

Uh, right, I have always treated example.com as a placeholder, didnt actually know it resolved to something. Will change.

2024-12-19 16:31 UTC, tomkralidis approved these changes

2024-12-19 16:31 UTC, merged